Workflow disabled

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -43,13 +43,14 @@ jobs:
       run: |
         pylint spg_experiments
 
-    - name: Run pytest
-      run: |
-        set -o pipefail
-        pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=spg_experiments tests/ | tee pytest-coverage.txt
+    # TODO: this fails currently in the Github workflow because of the CUDA requirements
+    # - name: Run pytest
+    #   run: |
+    #     set -o pipefail
+    #     pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=spg_experiments tests/ | tee pytest-coverage.txt
 
-    - name: Pytest coverage comment
-      uses: MishaKav/pytest-coverage-comment@main
-      with:
-        pytest-coverage-path: ./pytest-coverage.txt
-        junitxml-path: ./pytest.xml
+    # - name: Pytest coverage comment
+    #   uses: MishaKav/pytest-coverage-comment@main
+    #   with:
+    #     pytest-coverage-path: ./pytest-coverage.txt
+    #     junitxml-path: ./pytest.xml
